# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/WorkSpace/project/FPGA/prj_sc2238_v2.0_emmc_RGB/prj_sc2238_RGB/prj_sc2238_RGB.srcs/sources_1/ip/axis_dwidth_converter_0/axis_dwidth_converter_0.xci
# IP: The module: 'axis_dwidth_converter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/WorkSpace/project/FPGA/prj_sc2238_v2.0_emmc_RGB/prj_sc2238_RGB/prj_sc2238_RGB.srcs/sources_1/ip/axis_dwidth_converter_0/axis_dwidth_converter_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_dwidth_converter_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/WorkSpace/project/FPGA/prj_sc2238_v2.0_emmc_RGB/prj_sc2238_RGB/prj_sc2238_RGB.srcs/sources_1/ip/axis_dwidth_converter_0/axis_dwidth_converter_0.xci
# IP: The module: 'axis_dwidth_converter_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/WorkSpace/project/FPGA/prj_sc2238_v2.0_emmc_RGB/prj_sc2238_RGB/prj_sc2238_RGB.srcs/sources_1/ip/axis_dwidth_converter_0/axis_dwidth_converter_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_dwidth_converter_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
